// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCARGMjs7llmBtoQ_qMI-coAexckdctovc',
    appId: '1:923406327267:web:fe7082ad4e4e5c78ba54d6',
    messagingSenderId: '923406327267',
    projectId: 'farmtwin-f64bd',
    authDomain: 'farmtwin-f64bd.firebaseapp.com',
    storageBucket: 'farmtwin-f64bd.firebasestorage.app',
    measurementId: 'G-5JELCLJED8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDcwUvvNcF0-TAUB990ZKos3gX-tA04MM',
    appId: '1:923406327267:android:bd90de71d9968206ba54d6',
    messagingSenderId: '923406327267',
    projectId: 'farmtwin-f64bd',
    storageBucket: 'farmtwin-f64bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTptwwYDxICt63ZVGO8QzgX_uv-NlyGgM',
    appId: '1:923406327267:ios:003f20ca9a561057ba54d6',
    messagingSenderId: '923406327267',
    projectId: 'farmtwin-f64bd',
    storageBucket: 'farmtwin-f64bd.firebasestorage.app',
    iosClientId:
        '923406327267-g3462vdv2geq2jc2qialo1b5njjqefu4.apps.googleusercontent.com',
    iosBundleId: 'org.farmtwin.farmtwin',
  );
}
